name: b
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/githubuser/b#readme
license: BSD3
author: Author name here
maintainer: example@example.com
copyright: 2021 Author name here
category: Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - transformers
  - req
  - text
  - modern-uri
  - mtl
  - random

executables:
  b:
    source-dirs: src
    main: Main.hs
