name: echo-bot
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/prodderman/echo-bot
license: BSD3
author: prodderman
maintainer: example@example.com
copyright: 2021 prodderman
category: Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - transformers
  - req
  - text
  - modern-uri
  - mtl
  - random

library:
  source-dirs: src

executables:
  bot:
    source-dirs: src
    main: Main.hs
    dependencies: echo-bot

tests:
  echo-bot-test:
    main: Spec.hs
    source-dirs: tests
    dependencies:
      - tasty
      - tasty-hspec
      - echo-bot
